#  zfcraft配置文件

# setting of imgs
#贴图num
imgcount
7
#贴图修改为 sz * sz 大小
imgloadsize
32

# setting of world basic set
worldsize
1000
worldheight
384
#worldsize/height已定义为常量1000/384

# setting of world build
gentimes
1000
#平均的轮数
rand_qm
100
#高度极差
lower_ht
100
#最低高度
pingjun_num
25
#对几个数平均    <=50

##setting of world build - plants
# trees
tree_kfb
20

##setting of world build - kuagwu
# iron swan
iron_kfb
8
#iron的1000分比
iron_h
150
iron_l
1
#iron的生成范围
iron_tk_m
16
#iron的蔟最大数量

# setting of draw world
#none

# setting of window
window_x
800
window_y
600

# setting of main loop running
time_of_tick
100
#每tick最少时间，已废止
arm_len
6
#最多可以破坏/放置距离